import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/staticUI/header";
import Footer from "@/components/staticUI/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sheba Markets",
  description: "Generated by SHEBA MARKETS DEVELOPER TEAM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#0a0a0a]">
      <body
        className={`${robotoMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased lg:px-20 xl:px-40 `}
      >
        <Header/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
